import { Cliente } from "./clases/claseCliente.js";
import { Empleado } from "./clases/claseEmpleado.js";
import { Persona } from "./clases/clasePersona.js";

let persona1 = new Persona ('JUAN', 'PEREZ', 19);
let empleado1 = new Empleado ('Federica', 'López', 25, 22050.20);
let cliente1 = new Cliente ('AnTONio', 'García', 28, new Date());
console.log(persona1.toString());
console.log(empleado1.toString());
console.log(cliente1.toString());
let empleado2 = new Empleado (persona1.nombre, persona1.apellido, persona1.edad, 30000);
console.log(empleado2.toString());
let persona2 = new Persona ('Alejandro', 'Muñoz', 30);
console.log(persona2.toString());
console.log(`Id del empleado2: ${empleado2.id}`);
console.log(`Id del cliente1: ${cliente1.id}`);
console.log('Contador de personas: ' + Persona.contadorPersonas);
let p23 = new Persona();
console.log('Contador de personas: ' + Persona.contadorPersonas);
let p24 = new Persona();
console.log('Contador de personas: ' + Persona.contadorPersonas);
let p25 = new Persona();
console.log('Contador de personas: ' + Persona.contadorPersonas);
let p26 = new Persona();
console.log('Contador de personas: ' + Persona.contadorPersonas);
